name: nf-core-demultiplex-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## bioconda packages
  - fastqc=0.11.8
  - multiqc=1.7
  - bcl2fastq2=2.19.0
  - fastq-screen=0.13.0
  ##- cellrangermkfastq=3.0.2
  ##- cellrangercount=3.0.2
  - python=3.7.3
